In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
s = pd.Series([5,4,7,6,2,9,8,4,7,8,2])
print(s)
print(s.index)
print(s.values)
print(s[3:7])
print(7 in s)
print(s[(s>7) & (s<9)])

print('After the break\n\n\n\n')
s=pd.Series([4,6,7,8,6,5,4,5,6], index=['a','b','c','d','e','f','g','h','i'])
print(s)
print(s.index)
print(s.values)
print(s['c':'g'])
print(s['d'])
s['i']=100
print(s)
print('d' in s)
print(s[['c','e','h']])

0     5
1     4
2     7
3     6
4     2
5     9
6     8
7     4
8     7
9     8
10    2
dtype: int64
RangeIndex(start=0, stop=11, step=1)
[5 4 7 6 2 9 8 4 7 8 2]
3    6
4    2
5    9
6    8
dtype: int64
True
6    8
9    8
dtype: int64
After the break




a    4
b    6
c    7
d    8
e    6
f    5
g    4
h    5
i    6
dtype: int64
Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'], dtype='object')
[4 6 7 8 6 5 4 5 6]
c    7
d    8
e    6
f    5
g    4
dtype: int64
8
a      4
b      6
c      7
d      8
e      6
f      5
g      4
h      5
i    100
dtype: int64
True
c    7
e    6
h    5
dtype: int64

In [3]:
dict_population = {'sylhet':100, 'dhaka':200, 'rajshahi':300, 'barisal':400, 'maymansingh':500, 'chittaganj':600}
s = pd.Series(dict_population)
print(s)
print(s['dhaka':'maymansingh'])
print(s['barisal'])

sylhet         100
dhaka          200
rajshahi       300
barisal        400
maymansingh    500
chittaganj     600
dtype: int64
dhaka          200
rajshahi       300
barisal        400
maymansingh    500
dtype: int64
400

In [4]:
#constructing series
s = pd.Series([2,4,6,1,3,5])
print(s)
s = pd.Series(5, index=[2,4,6])
print(s)
s = pd.Series({2:'c', 1:'b', 3:'a'})
print(s)
s = pd.Series({'a':2, 'c':5, 'b':4}, index=['a','b'])
print(s)

0    2
1    4
2    6
3    1
4    3
5    5
dtype: int64
2    5
4    5
6    5
dtype: int64
2    c
1    b
3    a
dtype: object
a    2
b    4
dtype: int64

In [6]:
#WORKING WITH DATAFRAME

area_dict = {'sylhet':100, 'dhaka':200, 'rajshahi':300, 'barisal':400, 'maymansingh':500, 'chittaganj':600}
s = pd.Series(area_dict)
print(s)
population_dict = {'sylhet':100, 'barisal':200, 'dhaka':300, 'rajshahi':400, 'chittaganj':500, 'mymansingh':600}
df = pd.DataFrame({'population':population_dict, 'area':s})
print(df)
print(df.index)
print(df.columns)
print(df.values)
print(df['area'])

sylhet         100
dhaka          200
rajshahi       300
barisal        400
maymansingh    500
chittaganj     600
dtype: int64
             population   area
barisal           200.0  400.0
chittaganj        500.0  600.0
dhaka             300.0  200.0
maymansingh         NaN  500.0
mymansingh        600.0    NaN
rajshahi          400.0  300.0
sylhet            100.0  100.0
Index(['barisal', 'chittaganj', 'dhaka', 'maymansingh', 'mymansingh',
       'rajshahi', 'sylhet'],
      dtype='object')
Index(['population', 'area'], dtype='object')
[[200. 400.]
 [500. 600.]
 [300. 200.]
 [ nan 500.]
 [600.  nan]
 [400. 300.]
 [100. 100.]]
barisal        400.0
chittaganj     600.0
dhaka          200.0
maymansingh    500.0
mymansingh       NaN
rajshahi       300.0
sylhet         100.0
Name: area, dtype: float64

In [7]:
#constructing dataframe

area_dict = {'sylhet':100, 'dhaka':200, 'rajshahi':300, 'barisal':400, 'maymansingh':500, 'chittaganj':600}
s = pd.Series(area_dict)
df = pd.DataFrame(s, columns=['population'])
print(df)
#from a list
data = [{'a':i, 'b':i*2} for i in range(3)]
df = pd.DataFrame(data)
print(df)
df = pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])
print(df)
#from a dictionary
area_dict = {'sylhet':100, 'dhaka':200, 'rajshahi':300, 'barisal':400, 'maymansingh':500, 'chittaganj':600}
s = pd.Series(area_dict)
population_dict = {'sylhet':100, 'barisal':200, 'dhaka':300, 'rajshahi':400, 'chittaganj':500, 'mymansingh':600}
df = pd.DataFrame({'population':population_dict, 'area':s})
print(df)
#from a two dimentional numpy array
df = pd.DataFrame(np.random.rand(3,2), index=['a','b','c'], columns=['A','B'])
print(df)

             population
sylhet              100
dhaka               200
rajshahi            300
barisal             400
maymansingh         500
chittaganj          600
   a  b
0  0  0
1  1  2
2  2  4
     a  b    c
0  1.0  2  NaN
1  NaN  3  4.0
             population   area
barisal           200.0  400.0
chittaganj        500.0  600.0
dhaka             300.0  200.0
maymansingh         NaN  500.0
mymansingh        600.0    NaN
rajshahi          400.0  300.0
sylhet            100.0  100.0
          A         B
a  0.104987  0.595331
b  0.502460  0.499710
c  0.660475  0.611120

In [8]:
#pandas index object

ind = pd.Index([2,4,6,1,3,5])
print(ind)
print(ind[2])
print(ind[::2])
print(ind[1:4])
#index as orderset
indA = pd.Index([1,3,5,7,9])
indB = pd.Index([2,3,6,7,10])
print(indA & indB)
print(indA | indB)
print(indA ^ indB)

Int64Index([2, 4, 6, 1, 3, 5], dtype='int64')
6
Int64Index([2, 6, 3], dtype='int64')
Int64Index([4, 6, 1], dtype='int64')
Int64Index([3, 7], dtype='int64')
Int64Index([1, 2, 3, 5, 6, 7, 9, 10], dtype='int64')
Int64Index([1, 2, 5, 6, 9, 10], dtype='int64')

In [9]:
#use of loc, iloc, ix 
dict = {'A':[3,4,6,8,1,3,5,7,9], 'B':[1,3,5,7,9,2,4,6,8]}
df = pd.DataFrame(dict, index=['a','b','c','d','e','f','g','h','i'])
print(df)

a_loc = df.loc['g']
print(a_loc)
b_loc = df.loc['c':'g']
print(b_loc)
c_loc = df.loc['d':'g','A':'B']
print(c_loc)

print('after a big break \n\n\n\n\n')
a_iloc=df.iloc[3]
print(a_iloc)
b_iloc=df.iloc[3:7]
print(b_iloc)
c_iloc=df.iloc[2:6, 0:2]
print(c_iloc)

print('after a big break\n\n\n\n')
a_ix=df.ix[3:8, 'A':'B']
print(a_ix)

   A  B
a  3  1
b  4  3
c  6  5
d  8  7
e  1  9
f  3  2
g  5  4
h  7  6
i  9  8
A    5
B    4
Name: g, dtype: int64
   A  B
c  6  5
d  8  7
e  1  9
f  3  2
g  5  4
   A  B
d  8  7
e  1  9
f  3  2
g  5  4
after a big break





A    8
B    7
Name: d, dtype: int64
   A  B
d  8  7
e  1  9
f  3  2
g  5  4
   A  B
c  6  5
d  8  7
e  1  9
f  3  2
after a big break




   A  B
d  8  7
e  1  9
f  3  2
g  5  4
h  7  6

/home/hasan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
/home/hasan/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:822: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)

In [11]:
#dictionary in DataFrame

state = pd.Series({'sylhet':100, 'dhaka':200, 'chittaganj':300, 'rajshahi':400, 'barisal':500, 'maymansingh':600})
country = pd.Series({'chittaganj':300, 'rajshahi':100, 'dhaka':400, 'maymansingh':500, 'barisal':200, 'sylhet':600})
df = pd.DataFrame({'state':state, 'country':country})
print(df)
print(df.state)
print(df.state is df['state'])
print(df.country is df['country'])
print('after a big break\n\n\n\n')
#adding a new column in the DataFrame
df['distance'] = df['state']/ df['country']
print(df)
#DataFrame is converting to 2D array
print('after a big break\n\n\n\n')
print(df.values)
print(df.values[1])
print(df.T)
#use of ix in DataFrame
print('after a big break\n\n\n\n')
print(df)
print(df.ix['chittaganj':'rajshahi', 0:2])
#use of numpy-data access pattern
b = df[df.distance>2]
print(b)
a = df.loc[df.distance>=2, ['state','country']]
print(a)

#replaceing data of DataFrame
print('after a big break\n\n\n\n')
df.iloc[2,1] = 10000
print(df)

             state  country
barisal        500      200
chittaganj     300      300
dhaka          200      400
maymansingh    600      500
rajshahi       400      100
sylhet         100      600
barisal        500
chittaganj     300
dhaka          200
maymansingh    600
rajshahi       400
sylhet         100
Name: state, dtype: int64
True
True
after a big break




             state  country  distance
barisal        500      200  2.500000
chittaganj     300      300  1.000000
dhaka          200      400  0.500000
maymansingh    600      500  1.200000
rajshahi       400      100  4.000000
sylhet         100      600  0.166667
after a big break




[[5.00000000e+02 2.00000000e+02 2.50000000e+00]
 [3.00000000e+02 3.00000000e+02 1.00000000e+00]
 [2.00000000e+02 4.00000000e+02 5.00000000e-01]
 [6.00000000e+02 5.00000000e+02 1.20000000e+00]
 [4.00000000e+02 1.00000000e+02 4.00000000e+00]
 [1.00000000e+02 6.00000000e+02 1.66666667e-01]]
[300. 300.   1.]
          barisal  chittaganj  dhaka  maymansingh  rajshahi      sylhet
state       500.0       300.0  200.0        600.0     400.0  100.000000
country     200.0       300.0  400.0        500.0     100.0  600.000000
distance      2.5         1.0    0.5          1.2       4.0    0.166667
after a big break




             state  country  distance
barisal        500      200  2.500000
chittaganj     300      300  1.000000
dhaka          200      400  0.500000
maymansingh    600      500  1.200000
rajshahi       400      100  4.000000
sylhet         100      600  0.166667
             state  country
chittaganj     300      300
dhaka          200      400
maymansingh    600      500
rajshahi       400      100
          state  country  distance
barisal     500      200       2.5
rajshahi    400      100       4.0
          state  country
barisal     500      200
rajshahi    400      100
after a big break




             state  country  distance
barisal        500      200  2.500000
chittaganj     300      300  1.000000
dhaka          200    10000  0.500000
maymansingh    600      500  1.200000
rajshahi       400      100  4.000000
sylhet         100      600  0.166667

/home/hasan/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:22: FutureWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated